report_to_telegram_time: '08:00'      # ('HH:MM') Время ежедневной отправки отчета в Telegram
report_silently_every_hours: 4        # (int | float) Число часов между измерениями
mem_threshold: 100                    # (int | float) [Мбайт] При значениях доступной RAM ниже данного будет отображаться предупреждение
cpu_threshold: 80                     # (int | float) [%] При загрузке CPU выше данного значения будет отображаться предупреждение
disk_threshold: 3.0                   # (int | float) [Гбайт] При свободном дисковом пространстве ниже данного значения будет отображаться предупреждение